imports:
    - { resource: config.yml }

parameters:
    env(PAYBOX_SITE): "1999888"
    env(PAYBOX_RANK): "32"
    env(PAYBOX_IDENTIFIER): "107904482"
    env(PAYBOX_KEY): "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF"
    timeline_max_messages: 10

services:
    app.mailer.transactional_client:
        class: 'Tests\AppBundle\Test\Mailer\NullEmailClient'
        public: false

    app.mailer.campaign_client:
        class: 'Tests\AppBundle\Test\Mailer\NullEmailClient'
        public: false

    app.recaptcha.api_client:
        class: 'Tests\AppBundle\Test\Recaptcha\DummyRecaptchaApiClient'
        public: false

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type:   console
            channels: ["!event", "!doctrine"]
